name: Build uBlue images
on:
  push:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Bellatrix Image
        uses: blue-build/github-action@v1  
        with:
          recipe: bellatrix.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}      
      - name: Build Aethera image
        uses: blue-build/github-action@v1 
        with:
          recipe: aethera-dms.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}    
      - name: Build Hyprblue Image
        uses: blue-build/github-action@v1  
        with:
          recipe: hyprblue-dms.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build BlueMango Image
        uses: blue-build/github-action@v1
        with:
          recipe: bluemango-dms.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build BlueSway Image
        uses: blue-build/github-action@v1  
        with:
          recipe: bluesway-dms.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Bellatrix Image
        uses: blue-build/github-action@v1  
        with:
          recipe: bellatrix.yml 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}  
          registry_token: ${{ secrets.GITHUB_TOKEN }}