name: Build Installer ISO

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-interactive-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: bluemango
          image_repo: ghcr.io/guhnope
          image_tag: latest
          version: 43
          variant: ublue-os
          iso_name: bluemango-43.iso

      - name: Create Release and Upload ISO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the tag name if triggered by a tag, otherwise use 'latest'
          TAG_NAME=${{ github.ref_name }}
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG_NAME="latest"
          fi

          # Create or update the release and upload the files
          gh release delete $TAG_NAME --yes || true
          gh release create $TAG_NAME \
            ./output/bluemango-43.iso \
            ./output/bluemango-43.iso-CHECKSUM \
            --title "BlueMango Installer ($TAG_NAME)" \
            --notes "Automated build of BlueMango OS." \
            --latest