name: Build Interactive Installer ISO

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-interactive-iso:
    runs-on: ubuntu-latest
    container: 
      image: fedora:43
      options: --privileged

    steps:
      - name: Install dependencies
        run: dnf install -y lorax wget xorriso

      - name: Download Fedora 43 Net-Installer
        run: |
          wget -O base.iso https://mirror.aarnet.edu.au/pub/fedora/linux/releases/43/Server/x86_64/iso/Fedora-Server-netinst-x86_64-43-1.6.iso

      - name: Create Interactive Kickstart
        run: |
          cat <<EOF > kickstart.ks
          # Use Graphical mode so you can use the Partition Editor
          graphical

          network --bootproto=dhcp --device=link
          ostreecontainer --url=ghcr.io/guhnope/bluemango:latest --transport=registry --no-signature-verification
          EOF

      - name: Build ISO
        run: |
          # We still inject the UTF-8 fix to prevent the crash
          mkksiso --ks kickstart.ks --cmdline "inst.lang=en_US.UTF-8 inst.env=LC_ALL=en_US.UTF-8" base.iso bluemango.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: aethera-interactive
          path: aethera-interactive.iso
          retention-days: 5
